SELECT
  (SELECT CITY FROM STATION ORDER BY CHAR_LENGTH(CITY), CITY LIMIT 1) AS NOME_MENOR,
  (SELECT CITY FROM STATION ORDER BY CHAR_LENGTH(CITY) DESC, CITY LIMIT 1) AS NOME_MAIOR,
  (SELECT CHAR_LENGTH(CITY) FROM STATION ORDER BY CHAR_LENGTH(CITY), CITY LIMIT 1) AS TAM_MENOR,
  (SELECT CHAR_LENGTH(CITY) FROM STATION ORDER BY CHAR_LENGTH(CITY) DESC, CITY LIMIT 1) AS TAM_MAIOR;
